language: python
python:
#  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nosexcover
  - python setup.py install
# command to run tests
script:
  - python setup.py nosetests --with-xcoverage --cover-package=scapy_ssl_tls --cover-html --cover-branch --xcoverage-file=cover/cobertura.xml
